# Generated by Django 3.1.13 on 2021-12-21 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('kg', 'KILOGRAMO/S'), ('g', 'GRAMO/S'), ('cc', 'CENTIMETRO/S CUBICO/S'), ('lt', 'LITRO/S'), ('u', 'UNIDAD/ES')], default='gr', max_length=2)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'El producto ya existe en el inventario'}, max_length=30, unique=True)),
                ('category', models.CharField(choices=[('C', 'Cocina'), ('B', 'Bar')], default='C', max_length=1)),
                ('buy_price', models.FloatField(default=0)),
                ('sell_price', models.FloatField(default=0)),
                ('is_for_sale', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False, verbose_name='Numero')),
                ('is_free', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mesa',
                'verbose_name_plural': 'Mesas',
            },
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Mozo',
                'verbose_name_plural': 'Mozos',
            },
        ),
        migrations.CreateModel(
            name='StockQuantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measureunit')),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ingredient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='inventory.stock')),
                ('quantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measureunit')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Ingrediente para producto',
                'verbose_name_plural': 'Ingredientes para producto',
                'unique_together': {('ingredient', 'stock')},
            },
        ),
    ]
