# Generated by Django 3.1.13 on 2021-12-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='stock',
            field=models.ManyToManyField(to='inventory.Stock'),
        ),
    ]
