# Generated by Django 3.1.13 on 2021-12-03 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20211203_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='ammount',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='stock',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stock')),
            ],
        ),
    ]
