# Generated by Django 3.1.13 on 2021-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20211203_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
