# Generated by Django 3.1.13 on 2021-12-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20211205_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('number', models.AutoField(primary_key=True, serialize=False)),
                ('is_free', models.BooleanField(default=True)),
                ('waiter', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.waiter')),
            ],
        ),
    ]
