# Generated by Django 3.1.13 on 2021-12-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_auto_20211207_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_ingredient',
            field=models.BooleanField(default=True),
        ),
    ]
