# Generated by Django 3.1.13 on 2021-12-10 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20211210_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_ingredient',
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(error_messages={'unique': 'El producto ya existe en el inventario'}, max_length=30, unique=True)),
                ('quantity', models.IntegerField(default=1, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('buy_price', models.FloatField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['quantity'],
            },
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='inventory.ingredient'),
        ),
    ]
