# Generated by Django 3.1.13 on 2021-12-10 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20211210_2104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['name'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RemoveField(
            model_name='stock',
            name='buy_price',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='quantity',
        ),
    ]
