# Generated by Django 3.1.13 on 2021-12-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20211210_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.CharField(choices=[('C', 'Cocina'), ('B', 'Barra')], default='C', max_length=1),
        ),
    ]
