# Generated by Django 3.1.13 on 2021-12-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20211210_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['quantity'], 'verbose_name': 'Ingrediente', 'verbose_name_plural': 'Ingredientes'},
        ),
    ]
