# Generated by Django 3.1.13 on 2021-12-10 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20211210_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'verbose_name': 'Ingrediente para producto', 'verbose_name_plural': 'Ingredientes para producto'},
        ),
    ]
