# Generated by Django 3.1.13 on 2021-12-11 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20211211_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='waiter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.waiter'),
        ),
    ]
