# Generated by Django 3.1.13 on 2021-12-11 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20211211_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='waiter',
        ),
    ]
