# Generated by Django 3.1.13 on 2021-12-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_table_waiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='is_deleted',
            new_name='is_for_sale',
        ),
        migrations.AddField(
            model_name='stock',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='inventory.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('C', 'Cocina'), ('B', 'Barra')], default='C', max_length=1),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
