# Generated by Django 3.1.13 on 2021-12-12 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auto_20211212_1422'),
        ('inventory', '0023_auto_20211212_1422'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
