# Generated by Django 3.1.13 on 2021-12-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_auto_20211213_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit', models.CharField(choices=[('kg', 'KILOGRAM'), ('g', 'GRAMS'), ('cc', 'CUBIC CENTIMETER'), ('lt', 'LITER')], default='gr', max_length=2)),
                ('quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
