# Generated by Django 3.1.13 on 2021-12-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_stockquantity_measure_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientquantity',
            name='measure_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measureunit'),
        ),
    ]
