# Generated by Django 3.1.13 on 2021-12-17 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_ingredientquantity_measure_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='unit',
            field=models.CharField(choices=[('kg', 'KILOGRAMOS'), ('g', 'GRAMOS'), ('cc', 'CENTIMETROS CUBICOS'), ('lt', 'LITROS')], default='gr', max_length=2),
        ),
    ]
