# Generated by Django 3.1.13 on 2021-12-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20211217_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureunit',
            name='unit',
            field=models.CharField(choices=[('kg', 'KILOGRAMO/S'), ('g', 'GRAMO/S'), ('cc', 'CENTIMETRO/S CUBICO/S'), ('lt', 'LITRO/S'), ('u', 'UNIDAD/ES')], default='gr', max_length=2),
        ),
    ]
