# Generated by Django 3.1.13 on 2021-12-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_auto_20211218_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientquantity',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='stockquantity',
            name='quantity',
        ),
    ]
