# Generated by Django 3.1.13 on 2021-12-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20211219_1729'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockquantity',
            old_name='measure_unit',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='stock',
            name='category',
            field=models.CharField(choices=[('C', 'Cocina'), ('B', 'Bar')], default='C', max_length=1),
        ),
    ]
