# Generated by Django 3.1.13 on 2021-12-19 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_auto_20211219_2303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientquantity',
            old_name='measure_unit',
            new_name='quantity',
        ),
    ]
