# Generated by Django 3.1.13 on 2021-12-03 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salebilldetails',
            name='billno',
        ),
        migrations.DeleteModel(
            name='PurchaseBillDetails',
        ),
        migrations.DeleteModel(
            name='SaleBillDetails',
        ),
    ]
