# Generated by Django 3.1.13 on 2021-12-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20211203_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='perprice',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='totalprice',
            field=models.FloatField(default=1),
        ),
    ]
