# Generated by Django 3.1.13 on 2021-12-06 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20211205_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
