# Generated by Django 3.1.13 on 2021-12-07 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_auto_20211207_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tablesalebill',
            old_name='name',
            new_name='waiter',
        ),
    ]
