# Generated by Django 3.1.13 on 2021-12-07 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20211207_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesalebill',
            name='waiter',
        ),
    ]
