# Generated by Django 3.1.13 on 2021-12-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_table_waiter'),
        ('transactions', '0008_remove_tablesalebill_waiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablesalebill',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.table'),
        ),
        migrations.DeleteModel(
            name='Table',
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
