# Generated by Django 3.1.13 on 2021-12-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20211207_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchasebill',
            options={'verbose_name': 'Factura de compra', 'verbose_name_plural': 'Facturas de compra'},
        ),
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'verbose_name': 'Item de compra', 'verbose_name_plural': 'Items de compra'},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Item de venta', 'verbose_name_plural': 'Items de venta'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='tablesalebill',
            options={'verbose_name': 'Venta en mesa', 'verbose_name_plural': 'Ventas en mesa'},
        ),
    ]
