# Generated by Django 3.1.13 on 2021-12-11 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_table_waiter'),
        ('transactions', '0010_auto_20211207_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesalebill',
            name='waiter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.waiter'),
        ),
    ]
