# Generated by Django 3.1.13 on 2021-12-11 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_table_waiter'),
        ('transactions', '0011_tablesalebill_waiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='stock',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='inventory.ingredient'),
            preserve_default=False,
        ),
    ]
