# Generated by Django 3.1.13 on 2021-12-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20211212_1422'),
        ('transactions', '0012_auto_20211211_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='purchaseitem',
            name='stock',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchaseitem', to='inventory.stock'),
            preserve_default=False,
        ),
    ]
