# Generated by Django 3.1.13 on 2021-12-17 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_auto_20211217_2355'),
        ('transactions', '0013_auto_20211212_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseitem',
            name='quantity_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockquantity'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='quantity_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stockquantity'),
        ),
    ]
