# Generated by Django 3.1.13 on 2021-12-19 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_auto_20211219_1729'),
        ('transactions', '0016_remove_saleitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='quantity_of',
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.measureunit'),
        ),
    ]
