# Generated by Django 3.1.13 on 2021-12-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0017_auto_20211219_1807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchaseitem',
            options={'get_latest_by': 'billno__time', 'verbose_name': 'Item de compra', 'verbose_name_plural': 'Items de compra'},
        ),
    ]
