# Generated by Django 3.1.13 on 2021-12-20 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0018_auto_20211219_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='billno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salebillno', to='transactions.tablesalebill'),
        ),
    ]
