# Generated by Django 3.1.13 on 2021-12-20 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_auto_20211220_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='transactions.supplier'),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='billno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasebillno', to='transactions.purchasebill'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='billno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salebillno', to='transactions.tablesalebill'),
        ),
    ]
