# Generated by Django 3.1.13 on 2021-12-20 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_auto_20211220_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='billno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasebillno', to='transactions.purchasebill'),
        ),
    ]
