# Generated by Django 3.1.13 on 2021-12-20 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0021_auto_20211220_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasebill',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchasesupplier', to='transactions.supplier'),
        ),
    ]
